### ISSUE TITLE
Path to the cross compiler used ?

### ISSUE THREAD

**Issue by X-Ryl669** [ObooSmartClock/Oboo-Source#2]
Currently, the build system is a monster if one just wants to rebuild a package or debug an existing build (I don't really want to install/build 20GB of binaries just to compile a `.c` file for the Omega).

Do you have a simpler build example that would work on MacOS, for example ?
Ideally, I would like to only download the headers and a binary for the cross compiler used.

**Comment by greenbreakfast** [comment]
We've found the Docker image to work well for us. Especially since the Oboo software packages have dependencies on other packages/libraries in the build system.

On top of that, it would be too much overhead and room for errors to have different environments for development and release.

What I recommend is spinning up an AWS EC2 instance (there's a variety of free tier options) and using their Cloud9 IDE (also free).

**Comment by X-Ryl669** [comment]
What you are telling us here is that we all should use subpar development tools that are both slow (remote work) and not owned. I don't want to use a remote cloud service and spend a week to setup up and configure a tool I'll be only using for this, just for changing 2 lines to debug the card manager crash. 

I'm ok to spend time trying to fix the lame software of the Oboo since the hardware seems correctly done, but I'm not a contractual developer. I won't waste a week just to have an environment that "work for you". I already have my own tools to develop, I just need a cross compiler (or at least a compiler, since I have a Omega2 board too).

So please reconsider having an easier to bootstrap compiler so we can help improving this gizmo easily. Else, I'm sorry, but this is a too huge effort for me to apply and I'll ask for refund since the device is useless without the minimum stability and features you've advertised.
